#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import logging
import csv
from datetime import datetime, timedelta
from service import initialise_service

METRICS_DIR = os.environ['METRICS_DIR']
PREFIX = os.environ.get('PREFIX')
THRESHOLD_DAYS = int(os.environ.get('THRESHOLD_DAYS', 0))


def instream(filename):
    return open(filename, "r")


def run():
    logging.basicConfig(level=logging.INFO,
                        format='%(levelname)s:%(asctime)s: %(message)s')

    api = initialise_service()
    threshold = datetime.now() - timedelta(days=THRESHOLD_DAYS)
    for filename in os.listdir(METRICS_DIR):
        filepath = os.path.join(METRICS_DIR, filename)
        if filename.endswith('.csv') and os.path.getsize(filepath) > 0:
            f = instream(filepath)
            buff = csv.reader(f, delimiter=',', quotechar='"')
            next(buff, None)  # skip headers
            for row in buff:
                measure, timestamp, work_uri, country, event_uri, value = row
                if THRESHOLD_DAYS:
                    time = datetime.strptime(timestamp, '%Y-%m-%d %H:%M:%S')
                    if (time < threshold):
                        continue
                if not PREFIX or (PREFIX and work_uri.startswith(PREFIX)):
                    api.new_event(measure, timestamp, work_uri, country,
                                  event_uri, value)
            f.close()


if __name__ == '__main__':
    run()
